version: '3.3'

services:
  # db:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: ${DATABASE_USER}
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #   expose:
  #     # Opens port 3306 on the container
  #     - '3306'
  #     # Where our data will be persisted
  #   volumes:
  #     - my-db:/var/lib/mysql
  ownquest-api:
    image: ownquest-docker
    env_file:
      - .env
    ports:
      - "3000:3000"
# Names our volume
# volumes:
#   my-db:
